# 完整示例配置
base:
  log:
    enabled: true
    time-pattern: yyyy-MM-dd HH:mm:ss
  web:
    advice:
      enabled: true
    restTemplate:
      enabled: true
    info:
      enabled: true
      path: /info
      params:
        application: ${spring.application.name}
        port: ${server.port}
        version: 0.0.1
        desc: 项目介绍
  property:
    files: ["message.properties","exception.properties"]