spring:
  application:
    name: base-springboot-starter-test
server:
  port: 8080

base:
  log:
    enabled: true
    time-pattern: yyyy-MM-dd HH:mm:ss
  web:
    advice:
      enabled: true
    restTemplate:
      enabled: true
    info:
      version: 1.0.0
      desc: 基础项目
      enabled: true
  property:
    files: ["message.properties","exception.properties"]